# '''
# why python:
# 1. Easy syntax, more english like language..

# 2.open source..

# 3.Big community..

# 4.Plateform indeoendent..

# 5.vast library set: 2.35lakhs+ libraries/packages: billions  of predefined functions..

# 6. High level language..

# 7. python supports modular approach of programming...

# 8. we can divide the project into modular and finally interface all modules..

# 9. python is used in versatile domains....

# 10. DATA dariven domains: DATA ANALYTICS, MACHINE LEARNING,DEEEPLEARNING,IMAGEPROCESSING,NATHURAL LANGUAGE PROCESSING,
#      DATA SCIENCE,ARTIFICIAL INTELIGANCE..

# 11. OTHER DOMAINS WEB APPLICATION, MOBILE APPLICATION,IOT,CYBER SECURITY,NETWORK SECURITY,.....

# 12 . INTERPRETER BASED LANGUAGE:CODE LINE BY LINE EXECUTE...

# 13. PYTHON SUPPORTS DYNAMIC DATA TYPE DEFINITION : DTA TYPE DEFINTION AT RUN TIME...

# 14. PYTHON SUPPORTS DYNAMIC DATA MEMORY ALLOCATION : MEMORY ALLOCATION AT RUN TIME...

# 15. PLATEFORM INDEPENDENT: IF WE WRITE OUR CODE  IN ONE OS AND IF THE SAME CODE WITHOUT ANY CHANGE CAN BE
#     EXECUTED ON ANY OTHER OS ALSO THEN WE SAY OUR LANGUAGE OR TECHNOLOGY IS PLATEFORM INDEPENDENT:

# THIS IS WRONG DEFINITION. THIS IS THE DEFINTION OF PORTABILITY..

#   PORTABLE: WORA WRITE ONES RUN ANYWHERE
# PLATEFORM INDEPENDENT: CORA: COMPILE ONES RUN ANYWHERE : 

#  IF WE WRITE OUR CODE ON ONE OS AND COMPILE IT AFTER COMILATION IF OUR COMILED CODE CAN BE EXECUTED ON  ANY 
#   OS THEN WE CAN SAY OUR LANGUAGE OR TECHNOLOGY IS PLATEFORM INDEPENDENT

# COMPILE CODE: COMPILED CODE IS AN INTERMEDIATE CODE WHICH IS MORE CLOSER TO HARDWARE AND RUNS AT A FAST SPEED.

# IF WE OPEN OPEN A C ,JAVA AND PYTHON FILE IN NOTEPAD OR ANY TEXT EDITOR WHETHER CODE WILL BE HUMAN UNDERSTABLE...?
# yES,

# IF WE OPEN OPEN  THE COMPILED FILE OF A C ,JAVA AND PYTHON FILE IN NOTEPAD OR ANY TEXT EDITOR WHETHER CODE WILL BE HUMAN UNDERSTABLE...?
# NO

#  lWHETHER WE CAN CREATE A COMILED FILE IN PYTHON: YES
#  WE HAVE READY MADE LIBRARIES IN PYTHON THROUGH WHICH 
#  WE CAN CREATE COMPILE CODE PYTHON, EXTENTION OF PYTHON COMILED CODE FILE IS .PYC(PYTHON COMPILED CODE)

#  INTERPREER  VS COMPILER
#  INTERPRETER: LINE BY LINE CODE EXECUTION .MEANS LINE BY LINE ERROR ARE CHECKED. LINE BY LINE MEMORY IS ALLOCATED AND LINE BY LINEPROGRAM EXECUTED
#  EXAMPLE== PYTHON
# COMPILER: FIRSTLY COMPLETED CODE IS COMPILED MEANS ERROR ARE CHECKED IN THE CODE, 
# MEMORY IS ALLOCATED AND CODE BECOMES IN OBJECT CODE FORMAT. EXAMPLE C AND JAVA

# how much memory consumed by python..? it depends on the value
# dynamic memory allocation 


# Drawbacks:
# 1.pythons consumes a lot of memory
# 2.python is a slow processing language